### ISSUE TITLE
license.txt should be LICENSE.TXT

### ISSUE THREAD

**Issue by SteveALee** [ThePacielloGroup/aviewer#1]
Such a picky issue - but is easier to find that way

**Comment by matatk** [comment]
It seems we also have a [licence](https://github.com/ThePacielloGroup/aviewer/blob/master/licence) too -- fortunately they are the same licence :-).

Let's try this not-so-new-fangled TODO notation...
- [ ] Remove duplicate file
- [ ] Rename remaining one (check consistency of spelling [if there is any] across other TPG projects)

Thanks for the report, and also please note that this code is, probably, outdated (sorry) -- soon as I am able I am going to try to get it synched up with what's in WAT at the moment -- though that is the latest code for now.

**Comment by SteveALee** [comment]
And of course we should the US spelling LICENSE even though it is soooo wrong ;)
