### ISSUE TITLE
Feature request: Keyboard shortcuts

### ISSUE THREAD

**Issue by LJWatson** [ThePacielloGroup/aviewer#10]
Would be useful to have a keyboard shortcut for moving directly to each of the three panes (acc tree, acc properties and code view) within the UI. At present there is a lot of tabbing involved.

**Comment by patrickhlauke** [comment]
Fixed back in version 2.0, just never bothered to close this.

**Comment by patrickhlauke** [comment]
See https://github.com/ThePacielloGroup/aviewer/wiki#keyboard-shortcuts
