### ISSUE TITLE
issues with tree view and misreporting

### ISSUE THREAD

**Issue by stevefaulkner** [ThePacielloGroup/aviewer#13]
the latest developer branch exe has some issues: 
it does not always update the msaa etc info when walking the acc tree pane.
it does not always report correctly the element being watched via the cursor.

**Comment by LJWatson** [comment]
Confirmed.

**Comment by ghost** [comment]
Which browser are you using?
What should I do to reproduce them?

**Comment by stevefaulkner** [comment]
Hi JUn,
it occurs in Firefox and Chrome, I will provide a test page tomorrow

## 

Regards

SteveF
Current Standards Work @W3C
http://www.paciellogroup.com/blog/2015/03/current-standards-work-at-w3c/

**Comment by LJWatson** [comment]
It happens in Chrome 46 and Firefox 42 on my Windows 10 64bit machine.

**Comment by patrickhlauke** [comment]
This appears fixed to me (modulo https://github.com/ThePacielloGroup/aviewer/issues/26)
