### ISSUE TITLE
treeview no longer displays in Firefox 43

### ISSUE THREAD

**Issue by stevefaulkner** [ThePacielloGroup/aviewer#14]
Have tried current release version and dev versions, the left side treeviw does not display and the HTML/ARIA info does not display in the right list view. Occurs on very page viewed.

**Comment by ghost** [comment]
I can't reproduce it yet. Could you try reinstalling Firefox?

**Comment by stevefaulkner** [comment]
@jun325 works fine after re-install of firefox, thanks!
