### ISSUE TITLE
Create a proper Windows installer

### ISSUE THREAD

**Issue by patrickhlauke** [ThePacielloGroup/aviewer#16]
Similar to https://github.com/ThePacielloGroup/CCA-Win/issues/2, create a proper InnoSetup installer for aViewer

**Comment by stevefaulkner** [comment]
@jun325 can you take a look at doing this?

**Comment by patrickhlauke** [comment]
i think, as aViewer's a lot easier (no separate language files etc), that it's quite straightforward to create a simple InnoSetup file for it. will give it a try later tonight...

**Comment by stevefaulkner** [comment]
thanks @patrickhlauke, but we need to bring master up todate with dev branch

**Comment by ghost** [comment]
I think this script(https://github.com/ThePacielloGroup/aviewer/blob/Develop/package/aViewer.iss) goes well.

**Comment by patrickhlauke** [comment]
Yup seems to work ok :)
