### ISSUE TITLE
A little HOWTO would be nice

### ISSUE THREAD

**Issue by bjarniolsen** [ThePacielloGroup/aviewer#2]
Thank you for making a product helping me be a better webdeveloper!

But, at least for me, it's not that obvious how to use the Aviewer. Could you please add a little guide/howto, to help us get started?

Kind Regards
/Bjarni

**Comment by stevefaulkner** [comment]
Hi Bjarni,
I agree, its a time/resource issue
I don't know if you have seen this http://www.paciellogroup.com/blog/2013/03/aviewer-2013/ it may be helpful.

**Comment by bjarniolsen** [comment]
Hi Steve 

I totally understand :-)
I haven't seen that blogpost, thanks. That helps a lot.

Kind regards
/Bjarni

**Comment by matatk** [comment]
It may be worth re-opening this... right now I don't think we link to that 'blog post from anywhere within WAT or on the web pages about either WAT or aViewer.  Given that most people will probably meet aViewer via WAT, I think we should link to this documentation from there.  I'll re-open this and assign it to myself to keep track of this.  Thanks @bjarniolsen for reporting.

**Comment by bjarniolsen** [comment]
No problem :-)

**Comment by matatk** [comment]
Thanks to @patrickhlauke a link to the 'blog post was added to the README in ef1ed45139f40638401f4a6ca86a4298d984797e.

However I'll keep this open as I agree with Patrick that this is...

> while we wait to create a proper documentation in GitHub and as part of
> the download package itself

I agree; we should copy and update that post to either be part of the README here or some other documentation.

**Comment by patrickhlauke** [comment]
Did an initial transfer (minus images) of that blog post here to the wiki. https://github.com/ThePacielloGroup/aviewer/wiki

May at a future point add it as standalone docs that get installed together with the app, but for now i think that'll work.
