### ISSUE TITLE
Doesn't seem to work for me

### ISSUE THREAD

**Issue by jmuheim** [ThePacielloGroup/aviewer#20]
I have installed aViewer on Win7.

When opened, it sometimes displays a little bit on info, but it seems extremely laggy, and it crashes usually after focusing some random elements in Firefox.

![image](https://cloud.githubusercontent.com/assets/1814983/20531279/916ee532-b0d6-11e6-815d-3269c1bcf7b3.png)

Do I misunderstand something here?

**Comment by menovak** [comment]
hi jmuheim,

you have probably already tried this, but please check that you are using 32 or 64 bit aViewer in the proper Windows 7 OS (32 or 64 bit).

thanks
mark

**Comment by jmuheim** [comment]
As far as I see there's only one executable for download:

https://github.com/ThePacielloGroup/aviewer/releases/tag/2.0.0.0

When installing, there's no option to choose from 32/64bit.

I'm using Windows7 32bit.

**Comment by patrickhlauke** [comment]
Yes, the installer automatically selects the right binary (32/64bit). I will add that aViewer can *sometimes* be a bit...fickle/unstable on certain systems (particularly when there's many other apps running). I've known it to be particularly flaky in some cases with Firefox. :(

**Comment by jmuheim** [comment]
I'm using it in a "nearly virgin" windows 7 virtual machine (vmware fusion). So it shouldn't be because of many other apps or stuff like this.

**Comment by patrickhlauke** [comment]
Last thing I'd suggest is to check if you registered the dll (in settings). Beyond that I think this will be one of those cases where aViewer is showing its age/flakiness...

<img width="184" alt="aviewer3" src="https://cloud.githubusercontent.com/assets/895831/20557838/7e82d658-b16d-11e6-87bf-5d5fc49305c7.png">

**Comment by jmuheim** [comment]
I even can't click on this button without having the application crash. But thank you, I will deinstall the app, it doesn't seem to be useful to me this way.

Thanks for supporting.
