### ISSUE TITLE
Settings window has incorrect title

### ISSUE THREAD

**Issue by patrickhlauke** [ThePacielloGroup/aviewer#21]
It seems the settings window has incorrect/missing title - see screenshots below on a fresh install

<img width="372" alt="aviewer" src="https://cloud.githubusercontent.com/assets/895831/20557781/3e0bcfe4-b16d-11e6-9f95-00dab02c5ab7.png">

<img width="270" alt="aviewer2" src="https://cloud.githubusercontent.com/assets/895831/20557782/43bfb324-b16d-11e6-99eb-dc04b5d5327b.png">

**Comment by ghost** [comment]
I fixed it. https://github.com/ThePacielloGroup/aviewer/commit/8b85516a3dce3a81fc3b1494ff6001506d014726
