### ISSUE TITLE
aViewer and NVDA - NVDA announces any changes in treeview panel

### ISSUE THREAD

**Issue by patrickhlauke** [ThePacielloGroup/aviewer#24]
Not a bug, but more of an annoyance: when using aViewer and NVDA together, whenever the treeview panel gets updated, NVDA announces that change (often getting in the way of announcing what you're actually navigating, e.g. the content on a webpage).

See video https://youtu.be/MgYO2hieirY

**Comment by ghost** [comment]
I have just updated aViewer. Could you try new binary? https://github.com/ThePacielloGroup/aviewer/tree/Develop/package

**Comment by patrickhlauke** [comment]
Confirming that the latest binary fixes this. Great stuff!
