### ISSUE TITLE
empty tree view and code view in Firefox 52 and chrome 56 on windows 10 64 bit

### ISSUE THREAD

**Issue by stevefaulkner** [ThePacielloGroup/aviewer#26]
works fine in IE 11 not in firefox or chrome

**Comment by patrickhlauke** [comment]
hmm, seems to work for me in Chrome 57/Win 10/64bit 
> ![captureav](https://cloud.githubusercontent.com/assets/895831/24554139/6f69a8ce-1624-11e7-93dc-ba5cfbf1b8f9.PNG)

howver yes, in firefox i get a treeview with "<none>" in it
> ![captureavfx](https://cloud.githubusercontent.com/assets/895831/24554382/3bad6be6-1625-11e7-8a7e-ffa4edf22936.PNG)

**Comment by ghost** [comment]
I got the following return values.
Chrome(get_innerHTML function) returned failure code: 0x80004001(E_NOTIMPL)
Firefox(get_accChild function) returned failure code: 0x80070057(E_INVALIDARG)

And, I used and tried an old version of Firefox.
Firefox 50.0.2: S_OK
Firefox 51.0.1 and 53.0: E_INVALIDARG
Could you ask the mozilla team about this result of Firefox?

**Comment by stevefaulkner** [comment]
@jun325 I have asked 2 friends who are Mozilla acc engineers.

**Comment by stevefaulkner** [comment]
filed a bug on firefox after discussion with Alex and marco https://bugzilla.mozilla.org/show_bug.cgi?id=1363026

found there is same issue with inspect.exe

**Comment by stevefaulkner** [comment]
@jun325 

can you review this comment on the Firefox bug https://bugzilla.mozilla.org/show_bug.cgi?id=1363026#c8

They have marked as wontfix and described an alternative method for accessing the information.

**Comment by dbolter** [comment]
Will the alternative method work for you?

**Comment by ghost** [comment]
Thanks @stevefaulkner 
I have just uploaded the new version. https://github.com/ThePacielloGroup/aviewer/commit/225fb63f43ed2ca176ec61c0fdea3d868d84d4f4

**Comment by patrickhlauke** [comment]
https://github.com/ThePacielloGroup/aviewer/commit/225fb63f43ed2ca176ec61c0fdea3d868d84d4f4 does indeed fix this (tested in Win10)

**Comment by matatk** [comment]
On Chrome 63 on Windows 10, the tree is populated, but the HTML code isn't.

**Comment by ghost** [comment]
When I was investigating the cause of this issue, I found this source code(https://cs.chromium.org/chromium/src/content/browser/accessibility/browser_accessibility_com_win.cc?l=1381), and I tested HTML5+Mathml(https://www.tutorialspoint.com/html5/html5_mathml.htm).
Please see the screenshot below.
![ss1](https://user-images.githubusercontent.com/5038132/35667834-661a57ba-0772-11e8-840a-88fcccea3e87.jpg)
