### ISSUE TITLE
TreeView Pane: Cannot toggle TreeView pane between expanded/collapsed

### ISSUE THREAD

**Issue by jgauvreau** [ThePacielloGroup/aviewer#28]
I am using a Windows 7 SP1 64-bit laptop.

The Tree View pane can be collapsed but then it cannot be expanded. I found that this issue with the TreeView pane getting "stuck" collapsed happens if I manually use the mouse to click on the "Collapse (or Expand) Button for TreeView" [<< button] as well as if I use the View > Collapse > TreeView menu option.

1. Once I close the left TreeView pane (by clicking on the button or using the menu option) I can't get it to open again unless I close aViewer and reopen it and manually drag the pane open with my mouse. 
2. When I reopen aViewer then the TreeView pane is still visibly collapsed. The only way I can open it again is by manually using the mouse to drag the cursor to the right of the expand/collapse button. You cannot currently use the View > Collapse > Tree View menu option to toggle the pane back to an expanded state.
3. I currently cannot collapse/expand the panes using the keyboard to activate the buttons that control the panes. When I tab to the << button and activate it with the spacebar then aViewer becomes non-responsive. NOTE: I am able to repeatedly expand/collapse the two other panes (TreeList and CodeEdit) without a problem using either the mouse or the menu options but not by activating the buttons using the keyboard.

**Comment by patrickhlauke** [comment]
Should be fixed now in latest installer 2.0.3
