### ISSUE TITLE
Release 2.0.1.0: Number shown in Title bar says "Accessibility Viewer - 2.0.1.69"

### ISSUE THREAD

**Issue by jgauvreau** [ThePacielloGroup/aviewer#29]
On Windows 7, after I uninstalled my prior versions of aViewer and installed the new 2.0.1.0 version of aViewer when I open aViewer it shows a different version number (2.0.1.69) in the title bar of the window. See screenshot below.
![image](https://cloud.githubusercontent.com/assets/12006767/24558010/b72fed0c-1607-11e7-9b0a-ee7013e09038.png)

**Comment by patrickhlauke** [comment]
the 32bit and 64bit versions have slightly different minor sub-patch numbers, so for simplicity we round up the very last digit to 0 in the packaged version. something possibly simplified/addressed in future if it can be automated via innosetup
