### ISSUE TITLE
General instability/problems in Windows 7

### ISSUE THREAD

**Issue by patrickhlauke** [ThePacielloGroup/aviewer#30]
Trying the latest release on a Win7 virtual machine, and can confirm that it seems to hang/crash quite regularly (while under Win10 I'm not seeing these sorts of behaviors).

@jun325 wondering if you have a Win7 machine (either real or virtual) available to test? May be related to the IAccessible2.dll (particularly the 64bit one)?

**Comment by patrickhlauke** [comment]
xref https://github.com/ThePacielloGroup/aviewer/issues/27 and https://github.com/ThePacielloGroup/aviewer/issues/28

**Comment by ghost** [comment]
I built new windows 7 pc for more effective debugging the other day because I understood some problems on Windows 7.
Please give me some time.

**Comment by patrickhlauke** [comment]
sure, no rush

**Comment by ghost** [comment]
I have just updated the aViewer. Please try new binary files. 
32bit: https://github.com/ThePacielloGroup/aviewer/blob/Develop/package/aViewer32bit.exe
64bit: https://github.com/ThePacielloGroup/aviewer/blob/Develop/package/aViewer64bit.exe

**Comment by patrickhlauke** [comment]
took this for a spin in my win7 VM. seems to work quite nicely now with no crashes...will do some more testing and if nothing bad happens may wrap this up as a new release if that's ok @jun325 ? (so next version needs to up the version number etc as always)
