### ISSUE TITLE
Small tweak to version/product numbering

### ISSUE THREAD

**Issue by patrickhlauke** [ThePacielloGroup/aviewer#31]
Following the recent change in version numbering (which is a great start), I was wondering if we could have a further tweak...

Currently, the 32bit and 64bit versions have subtly different file version numbers (2.0.1.85 and 2.0.1.69) and the same product version (2.0.1.0). I've changed the InnoSetup file to grab the latter for the installer (so the combined installer becomes `aViewer2.0.1.0.exe`). However, this can be a little confusing (see https://github.com/ThePacielloGroup/aviewer/issues/29).

Is it possible to drop the last part of the product version, so it's just "2.0.1"? (or well, for the next release, "2.0.2")?

**Comment by patrickhlauke** [comment]
> ![aviewer](https://cloud.githubusercontent.com/assets/895831/24565596/c3b9a360-164d-11e7-89ab-f2141d791633.PNG)

**Comment by patrickhlauke** [comment]
To be clearer: the "file version" can certainly keep the last digits (the ".85" and ".69" etc) if that's something that's bumped up automatically every time it's compiled. This would just be about the "product version" being the same between those two - and, as discussed before, being reasonably strict about using http://semver.org/ with MAJOR.MINOR.PATCH numbering for that part

> MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards-compatible manner, and
PATCH version when you make backwards-compatible bug fixes.

**Comment by ghost** [comment]
I stopped automatic increment, and dropped it.
![ssav](https://cloud.githubusercontent.com/assets/5038132/25604763/0732acd4-2f41-11e7-80c8-ae393ebc2256.JPG)
