### ISSUE TITLE
New app icon

### ISSUE THREAD

**Issue by patrickhlauke** [ThePacielloGroup/aviewer#32]
For consistency with the TPG brand (and to make it slightly more visually appealing), started work on a new icon in a separate branch https://github.com/ThePacielloGroup/aviewer/tree/new-app-icon

Work is not complete here, as I believe the following still need to be resolved:

- [x] convert all `png` files into a multi-image `ico`
- [x] recompile the 32bit and 64bit `exe` files to use the new icon

**Comment by patrickhlauke** [comment]
@jun325 if you have any experience in the creation of appropriate multi-image `ico` files, give me a shout and we can coordinate

**Comment by patrickhlauke** [comment]
For reference, adding the large version and 16x16 version here.

![256x256](https://cloud.githubusercontent.com/assets/895831/26066767/eb29be34-398f-11e7-8a92-329db1533bce.png)

![16x16](https://cloud.githubusercontent.com/assets/895831/26066775/ee3be2b4-398f-11e7-95dd-7d18490c5832.png)

**Comment by patrickhlauke** [comment]
seem to have managed to create a multi-image `ico` file, but not sure if it's correct https://github.com/ThePacielloGroup/aviewer/commit/4d01995d14ee018c42280876cb3bb9560e713c68

**Comment by patrickhlauke** [comment]
Tested the `ico` by creating a shortcut to an `exe` and manually assigning the `ico` to this shortcut, then resizing the icons in file explorer. At list size, it correctly shows the custom 16x16 version, so assuming the multi-image `ico` is correct. I've now merged the separate branch into `Develop` ... @jun325 could you recompile the 32bit and 64bit versions using the new `Aviewer_Icon.ico` file in the development branch? This should then hopefully result in the nice multi-image version being used for the executable at different sizes, and the custom 16x16 to appear in the application window title bar, I assume. Then I can package this up for next release :)

**Comment by patrickhlauke** [comment]
(fair warning that I'll do a new icon for CCA-Win as well in the coming days)

**Comment by ghost** [comment]
I changed it.  https://github.com/ThePacielloGroup/aviewer/commit/225fb63f43ed2ca176ec61c0fdea3d868d84d4f4

**Comment by patrickhlauke** [comment]
Perfect, thanks @jun325
