### ISSUE TITLE
Windows 7 x64 support

### ISSUE THREAD

**Issue by oscarcao** [ThePacielloGroup/aviewer#4]
When trying to run aviewer on Windows 7 x64. The only thing that appears on screen is the aviewer taskbar icon.

**Comment by patrickhlauke** [comment]
@oscarcao i know it's a bit late...but: mind checking if the latest release still has this problem? https://github.com/ThePacielloGroup/aviewer/releases/tag/2.0.1.0

**Comment by patrickhlauke** [comment]
testing this in a Win7/64bit VM, it seems the problem as originally stated is resolved (though there are still problems with Win7 https://github.com/ThePacielloGroup/aviewer/issues/30). Closing for now
