### ISSUE TITLE
Quick Release

### ISSUE THREAD

**Issue by matatk** [ThePacielloGroup/aviewer#5]
Start using GitHub releases to distribute this.

**Comment by matatk** [comment]
I've just tried downloading and running [the latest 64-bit exe](https://github.com/ThePacielloGroup/aviewer/blob/master/Win64/Aviewer.exe) and run it, and it works very well (Windows 8.1, IE 11).  I was actually surprised by this, because I thought that it required a DLL file in order to run.

I did notice two problems:
1. That the settings box did not look correct:
   ![screen shot 2015-08-05 at 21 01 24](https://cloud.githubusercontent.com/assets/1125522/9096466/2ff4f874-3bb5-11e5-8329-238e4d75f187.png)
2. Also, the second-to-last button on the toolbar did not function.

However I do not know if these problems are related to the EXE being on its own.

@jun325: Would you expect aViewer (32- or 64-bit) to work fine with just the EXE?  (Sorry for the rather basic question, and thanks in advance :-).)

**Comment by matatk** [comment]
Partially answering my own question... the following three things, as well as the EXE, seem to be necessary... (the problem with the settings dialog, above, is now fixed)
- lang/
- aviewer.ini
- IAccessible2Proxy.dll

Where all of these (particularly the DLL) written by @jun325?  Just need to check that we are allowed to redistribute them, then need to work out the best way to package them ASAP (longer-term, we should probably all talk about something like #3).

Thanks!

**Comment by stevefaulkner** [comment]
> Where all of these (particularly the DLL) written by @jun325? Just need to check that we are allowed to redistribute them

we have always redistributed the Iaccessible2proxi.dll so no problem there, please go ahead and create a package.

**Comment by matatk** [comment]
I have created such a release as described above: https://github.com/ThePacielloGroup/aviewer/releases/tag/2015-08-13

@stevefaulkner @patrickhlauke are you able to test this on 32- as well as 64-bit Windows? I have only 64-bit.

**Comment by matatk** [comment]
Result! @menovak has tested this 'quick release' and it works fine on 32- and 64-bit Windows.

I have marked it as an official release.  It is not yet integrated into WAT (this will require more thought).

@patrickhlauke please could you point the website at https://github.com/ThePacielloGroup/aviewer/releases/latest ?

Here is the [github help topic on linking to the latest release](https://help.github.com/articles/linking-to-releases/).

**Comment by patrickhlauke** [comment]
Done http://www.paciellogroup.com/resources/aviewer/
