### ISSUE TITLE
watch focus does not work in Firefox 39

### ISSUE THREAD

**Issue by stevefaulkner** [ThePacielloGroup/aviewer#8]
tested on http://thepaciellogroup.github.io/AT-browser-tests/test-files/a-href.html
no focus ring is displayed and no information is displayed when the link has focus.

**Comment by ghost** [comment]
I understand UIA and yellow focus ring bug. And, I will fix them by the end of this month.
Or, is it a red focus ring problem? Please try this version. https://github.com/ThePacielloGroup/aviewer/blob/Develop/Win32/Aviewer.exe

**Comment by stevefaulkner** [comment]
thanks jun, works fine
