### ISSUE TITLE
64 bit version not working correctly

### ISSUE THREAD

**Issue by stevefaulkner** [ThePacielloGroup/aviewer#9]
the latest build of 64 bit version does not show IA2

**Comment by matatk** [comment]
Possibly related to #4?

**Comment by ghost** [comment]
I couldn't find the 64-bit IAccessible2Proxy.dll on the internet. However, I compiled it because I found source code.
1. close Firefox and Chrome
2. overwrite dll https://github.com/ThePacielloGroup/aviewer/blob/Develop/Win64/IAccessible2Proxy.dll
3. execute aViewer
4. unreg and rereg

**Comment by patrickhlauke** [comment]
Resolved in latest release
